### ISSUE TITLE
Spacing and sizing slightly wrong when set as Homepage compared to new tab.

### ISSUE THREAD

**Issue by viato115** [migueravila/Bento#121]
It seems like the spacing and size of the buttons and lists are slightly wrong when set as my firefox homepage, compared to when set as new tab using the "Custom New Tab Page" addon. The new tab one is actually how it's supposed to look. I only changed some links in the config.js file, nothing else. I really have no idea what may cause this. I've tried using the default bento settings, reinstalling firefox, clearing cache etc.
I've added two screenshots to show what I mean. I'm using FIrefox 112.0.1 (64 Bit).

![Homepage](https://github.com/migueravila/Bento/assets/133047323/63c641a3-69e8-4663-a575-4a2f531a3dc3)
![NewTab](https://github.com/migueravila/Bento/assets/133047323/5e618ed8-59c6-49d1-a542-86c0cbae190f)

**Comment by lewisdoesstuff** [comment]
Does this only occur when opening Bento with the custom new tab extension, or does opening your instance on GitHub Pages directly show the same issue?

**Comment by viato115** [comment]
Opening it via Github Pages or manually typing in the link gives the same result as what I see when I launch Firefox (the Homepage one, which would be the "wrong" one). Launching FIrefox with the extension removed also shows the weirdly spaced Homepage.

**Comment by viato115** [comment]
So I really don't know what caused this, but after uninstalling firefox and deleting pretty much everything I could find with fzf -e again, reinstalling firefox and then reconfiguring bento and simplefox again, it now works as it should...
Thank you though for the quick reply! :)
