### ISSUE TITLE
How to put information in French

### ISSUE THREAD

**Issue by GrimlocK38** [migueravila/Bento#28]
Hi,

Wonderful start page :)

Two little questions :

1. can we do the translation in French ?

<img width="1529" alt="weather" src="https://user-images.githubusercontent.com/19632490/115137520-eec4ac00-a026-11eb-8130-c65d72d7e10c.png">

2. I uncomment the line to display the wallpaper but it does not appear
<img width="595" alt="background" src="https://user-images.githubusercontent.com/19632490/115215811-281f1980-a104-11eb-9d31-1fd286518116.png">

Thanks

**Comment by vlag24** [comment]
hello,
I'm French too

I did this to hide it : 
go to  Bento/sass/main.scss 
and uncomment a few lines :

![21⁄04⁄21-18h58](https://user-images.githubusercontent.com/6505894/115592787-35363700-a2c3-11eb-94be-b89e0d1e15bb.png)

**Comment by GrimlocK38** [comment]
Hi @vlag24,

Thanks for the response. after uncommenting it didn't change anything. Weird.

<img width="224" alt="bento" src="https://user-images.githubusercontent.com/19632490/115594898-91ef1d00-a2d6-11eb-8c51-fe99f9f9c5f8.png">

**Comment by vlag24** [comment]
well, on my computer I have to refresh several times before seeing at the changes... it's working for me though, yes weird !

**Comment by GrimlocK38** [comment]
@vlag24 

ok. I will clean my browser's cache. I'll keep you informed.

**Comment by vlag24** [comment]
@GrimlocK38 
maybe an onother way to hide it (not tested):
comment one line in Bento/js/weather.js
![21⁄04⁄21-19h52](https://user-images.githubusercontent.com/6505894/115598920-7aaa3280-a2ca-11eb-8333-40e70ed00aa4.png)

**Comment by GrimlocK38** [comment]
@vlag24 

Perfect :). on the other hand the very bizarre translation. does not apply for the moment
<img width="336" alt="weather" src="https://user-images.githubusercontent.com/19632490/115599727-36c02900-a2dc-11eb-88ec-4f1d7ad14a8a.png">

**Comment by vlag24** [comment]
@GrimlocK38 great ! I did it myself too

**Comment by GrimlocK38** [comment]
@vlag24,

Good :). Thanks for help.

by cons I wanted to display the wall.jpg but even uncommenting the wallpaper is not displayed. you were able to test ?

**Comment by vlag24** [comment]
sorry, no. Not yet, but I red some comments ( https://www.reddit.com/r/unixporn/comments/kt1qlg/plasma_my_first_rice_on_endeavouros_with_kde/gk50xzv/?utm_source=reddit&utm_medium=web2x&context=3) in which some guy did not succeed...
For now I'm struggling with the timezone : the time is showing 20:28 right now, but it's 22:28 in my timezone. Didn't found how to change it... will see tomorrow ;-)

**Comment by GrimlocK38** [comment]
@vlag24 

Hi, How are you. concerning the wallpaper ok. i go have see. for the time zone I did not touch anything on my side.

we keep up to date.

**Comment by vlag24** [comment]
@GrimlocK38 hello, fine thank you, hope you also
I found the fix for my timezone issue, here the fix which could help people with the same problem, go to Bento/js/time.js and :
![22⁄04⁄21-14h27](https://user-images.githubusercontent.com/6505894/115714271-76cbee00-a366-11eb-84bc-dce5839501c1.png)
voilà !
If you need help for the wallpaper to display, I will try to search for a fix later today. cheers !

**Comment by GrimlocK38** [comment]
@vlag24 
 
Yeah. very well also. thanks. Perfect for the timezone 😉

I modified in these places but nothing helps (wallpaper)
`main.css and style.css` but nothing

<img width="602" alt="main" src="https://user-images.githubusercontent.com/19632490/115721526-6aec2600-a37e-11eb-8876-7a0852e82e71.png">

<img width="291" alt="style" src="https://user-images.githubusercontent.com/19632490/115721531-6cb5e980-a37e-11eb-82bc-a4cf6ada61b4.png">

**Comment by vlag24** [comment]
@GrimlocK38 well I tried for more than 30 minutes to find a solution without any luck :(
I will try again later...

**Comment by GrimlocK38** [comment]
@vlag24

there is another part that blocks because I think where I was seems coherent to me. we will get there :)

**Comment by vlag24** [comment]
@GrimlocK38 
you're right but yesterday and today, it tried to change some codes multiples times without any luck, again... well, I'll let the white background for now. If someone found a way... don't hesitate to share it ;-)

**Comment by GrimlocK38** [comment]
@vlag24,

Hi, If I have something new, yes I will come back to let you know 😉. Thanks again

**Comment by migueravila** [comment]
Hi @GrimlocK38 @vlag24 !!! In the new version of Bento you can enable the Background just changing the `config file`. You just need to fork the repo again!
