### ISSUE TITLE
Offline / Caching Support?

### ISSUE THREAD

**Issue by Syakhisk** [migueravila/Bento#30]
I really like Bento, but I don't always have good internet access. Is there a way to load the page faster? Like caching or make it offline?

**Comment by migueravila** [comment]
Hey @Syakhisk Bento is a project meant to be a self hosted startpage. I'll work on a less heavy version and I'll improve the code quality so it would be faster to run

**Comment by migueravila** [comment]
Hello! @Syakhisk I've checked the performance of the web page with this new version. 

![Screenshot_2021-07-23-42_494x162](https://user-images.githubusercontent.com/35583825/126857765-a7ccdb4c-8c99-43a6-85c4-50660de946c8.png)
