### ISSUE TITLE
Cannot change off white theme

### ISSUE THREAD

**Issue by Someone-Not-Important** [migueravila/Bento#33]
I cannot change off of the light theme. Clicking on the toggle option doesn't work.

I've also tried replacing the CSS values for the light theme with the ones in the dark theme, hasn't worked.

**Comment by puppeht** [comment]
My workaround is to change the values in the style editor in inspect element. Would like to know if this is a "just me" type issue.

**Comment by migueravila** [comment]
Hey @Someone-Not-Important, It should be a 'just me' Issue. Still, try forking again the repository. There's a new version of Bento available now!
