### ISSUE TITLE
Toggle between multiple dashboards

### ISSUE THREAD

**Issue by IAmSurajBobade** [migueravila/Bento#36]
Can we add a profile toggle that will allow users to select multiple versions of this Bento dashboard?

Mockup:
Following is an example, where you can see two profiles Work and Home 
![image](https://user-images.githubusercontent.com/11486375/126859844-073c36e6-7700-45b2-82ed-b0c5c09f567a.png)

**Comment by migueravila** [comment]
Hi! @IAmSurajBobade. I don't think it'll be the scope or a goal for the project. A workaround could be making two forks for the project and use one or another depending your mood.
