### ISSUE TITLE
Add multi-language support

### ISSUE THREAD

**Issue by JaquesBoeno** [migueravila/Bento#37]
**hello, i'm brazilian and i apologize in advance because i can't speak english so i'm using google translator,**
one of the things I missed about Bento was the weather forecast in Portuguese so I looked in the api documentation for a way to solve this, and I ended up finding a solution to send the 'lang' parameter in the url with the language you want as a result, so i did this and add the parameter 'languge' in the config.js file and send it along with the api request.

[my repository with this solution](https://github.com/JaquesBoeno/Bento)

**Comment by migueravila** [comment]
Hey @JaquesBoeno I've just added this feature. Thank you so much for your repo!
