### ISSUE TITLE
White flash when opening Bento

### ISSUE THREAD

**Issue by WildRage1369** [migueravila/Bento#44]
When I open Bento, a white flash appears, i.e. the background starts white then fades to black. The image shows how the page looks for less than a moment when it first starts:
![](https://user-images.githubusercontent.com/36650430/130906815-be9bd36f-dab5-4697-8261-79a408888cfe.png)
This is annoying especially late at night when a white flash can be disorienting. Is there a way to fix this or is this intended?

**Comment by migueravila** [comment]
💌 Solved in #38
