### ISSUE TITLE
Request: Add spotify currently playing music

### ISSUE THREAD

**Issue by CoolGuyMK** [migueravila/Bento#78]

**Comment by CoolGuyMK** [comment]
Something like this:
![IMG_20220317_101223](https://user-images.githubusercontent.com/63323163/158765408-91ed6034-b5d1-4bd3-a4c5-08cf2c6d9ae9.jpg)

Sorry for the bad quality

**Comment by migueravila** [comment]
Hi! @CoolGuyMK I think It could be an awesome widget idea but It doesn't follow the design philosophy of the main project. Still if someone who clones the repo and makes it, I would add it to the Readme!
