### ISSUE TITLE
Provide a docker image

### ISSUE THREAD

**Issue by bgalvao** [migueravila/Bento#79]
It would be great to have this deployable as a docker container. I could even work on this.

**Comment by lewisdoesstuff** [comment]
I've got a docker image hosted of this currently, and there's an open PR for it. 
Hosted at [lewisdoesstuff/bento](https://hub.docker.com/r/lewisdoesstuff/bento).

There's a Dockerfile and docker-compose in my fork of this repo as well if you'd like.
Instructions for usage either in the dockerhub description or in the README of my fork.

**Comment by migueravila** [comment]
@bgalvao I've just accepted the PR #76 by @lewisdoesstuff to support docker deployment
